### ISSUE TITLE
Won't run on Minecraft version 1.8.9

### ISSUE THREAD

**Issue by hcorion** [Tbsc/TbscFPS#2]
Using:
Minecraft 1.8.9
Java 1.8.0_72
Forge1.8.9-11.15.1.1732
tbscfps-1.1 (for minecraft 1.8)
Windows 10

I get the following error when launching:
Forge Mod Loader has found a problem with your minecraft installation
The mod listed below does not want to run in Minecraft version 1.8.9
TbscFPS (tbscfps) wants Minecraft [1.8,1.8]

**Comment by Tbsc** [comment]
Yeah, it won't run on 1.8.9 because I have built it for 1.8. I can compile it fairly quickly to 1.8.9.

**Comment by Tbsc** [comment]
I also just reinstalled my PC and haven't setup everything for mod development, so a bit more extra time for me to set everything up (mostly compiling and decompiling)

**Comment by Tbsc** [comment]
Fixed, download v2.1 **for 1.8** (noting that there are 2 v2.1: the 1.7.10 version and 1.8.9 version)
